version: "3"

dotenv:
  - .env

tasks:
  gateway:
    cmd: go run ./backend/service/gateway

  build:
    cmds:
      - go mod tidy
      - docker buildx build --file ./deployments/docker/builder.Dockerfile -t service-builder:latest .

  up:
    dir: ./deployments/docker
    cmds:
      - task: build
      - docker compose up -d --build

  down:
    dir: ./deployments/docker
    cmd: docker compose down

  restart:
    cmds:
      - task: down
      - task: up
