services:
  balancer:
    image: nginx:1.27.2-alpine3.20
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./configs/nginx:/etc/nginx/templates
    depends_on:
      - rpc-gateway

  rpc-gateway:
    restart: unless-stopped
    build:
      args:
        SERVICE: gateway
      dockerfile: service.Dockerfile
    depends_on:
      - queue

  rpc-worker:
    restart: unless-stopped
    build:
      args:
        SERVICE: worker
      dockerfile: service.Dockerfile
    depends_on:
      - queue

  queue:
    image: nats:2.10.22-alpine3.20
    restart: unless-stopped
    volumes:
      - ./configs/nats/nats-server.conf:/etc/nats/nats-server.conf

  # database:
  #   image: postgres:14
  #   restart: unless-stopped
  #   # ports:
  #   #   - "127.0.0.1:5432:5432"
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data


  # rpc-gateway-02:
  #   restart: unless-stopped
  #   build:
  #     args:
  #       SERVICE: gateway
  #     dockerfile: service.Dockerfile

  # rpc-gateway-03:
  #   restart: unless-stopped
  #   build:
  #     args:
  #       SERVICE: gateway
  #     dockerfile: service.Dockerfile

volumes:
  postgres-data:

# networks:
  
  