services:
  balancer:
    image: nginx:1.27.2-alpine3.20
    restart: unless-stopped
    labels:
      logging: "promtail"
    ports:
      - 80:80
    volumes:
      - ./configs/nginx:/etc/nginx/templates
    depends_on:
      - gateway

  database:
    image: postgres:14
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: