services:
  promtail:
    image: grafana/promtail:latest
    restart: unless-stopped
    command: -config.file=/etc/promtail/config.yaml
    volumes:
      - ./configs/grafana/promtail-config.yaml:/etc/promtail/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - loki

  loki:
    image: grafana/loki:latest
    restart: unless-stopped
    ports:
      - 127.0.0.1:3100:3100
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - loki-data:/loki
      - ./configs/grafana/loki-config.yaml:/etc/loki/config.yaml

  prometheus:
    image: prom/prometheus:v2.55.1
    restart: unless-stopped
    ports:
      - 127.0.0.1:19090:9090
    volumes:
      - prometheus-data:/prometheus
      - ./configs/grafana/prometheus-config.yaml:/etc/prometheus/prometheus.yml
    

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki

volumes:
  grafana-data:
  loki-data:
  prometheus-data:
